name: Windows tests

on: [push, pull_request]

jobs:

  windows:
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        arch:  [amd64, x86, arm64]
        stfl_opt: [ON, OFF]
    steps:
      - uses: actions/checkout@v4
      - name: Generate Project
        run: cmake -B build --toolchain .CMake/toolchain_windows_${{ matrix.arch }}.cmake -DOQS_ENABLE_SIG_STFL_LMS=ON -DOQS_ENABLE_SIG_STFL_XMSS=ON -DOQS_HAZARDOUS_EXPERIMENTAL_ENABLE_SIG_STFL_KEY_SIG_GEN=${{ matrix.stfl_opt }} .
      - name: Build Project
        run: cmake --build build
      - name: Test dependencies
        run: pip.exe install pytest pytest-xdist pyyaml
      - name: Run tests
        # Setup Python in github marketplace doest not support arm64 yet
        if: matrix.arch != 'arm64'
        run: cmake --build build --target run_tests
